openai_key = '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'

PINECONE_API_KEY = 'b7815af0-d372-4b02-85ac-c473a1943767'
PINECONE_ENV = 'asia-southeast1-gcp-free'

notion_secret = 'secret_081DkYDYw98pMHw99e4OswDObvbT989hkdPytIj7jFN'

mysql_url =  'mysql+mysqlconnector://chinfi:SYXMPPe4LD2Facyf@121.36.220.157:3306/dd_spider'