openai_key = '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'
jina_key = 'u6OStwAGvCOimFbDqrnP:a398d6f33dc5ab57222a77352192d0b2fcfdae776a54cd27a1e94b5bb04f2ae8'

PINECONE_API_KEY = 'b7815af0-d372-4b02-85ac-c473a1943767'
PINECONE_ENV = 'asia-southeast1-gcp-free'
mysql_url =  'mysql+mysqlconnector://chinfi:SYXMPPe4LD2Facyf@121.36.220.157:3306/dd_spider?charset=utf8mb4'

notion_secret = 'secret_081DkYDYw98pMHw99e4OswDObvbT989hkdPytIj7jFN'
notion_prompt_database ='4c1a46916073441695d7cf0f3ca7ba57'

alpha_vantage_key = 'X1V6MXF4TJYPBNLL'